### ISSUE TITLE
append style file options

### ISSUE THREAD

**Issue by marcstreeter** [wbolster/jsonlines#93] opened 2023-09-13 12:23 UTC
using `jsonlines` with standard file opening semantics

```
with jsonlines.open(output, "w+") as writer:
   ...
```

results in errors

```
  File "/usr/local/bin/tqa", line 18, in parse
    with jsonlines.open(output, "w+") as writer:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.11/site-packages/jsonlines/jsonlines.py", line 639, in open
    raise ValueError("'mode' must be either 'r', 'w', 'a', or 'x'")
```

**Comment by wbolster** [comment] 2023-09-13 13:42
@marcstreeter what would you expect `w+` to do?

the `+` in a [open()](https://docs.python.org/3/library/functions.html#open) mode means

> open for updating (reading and writing)

… which makes little sense for `jsonlines.open()` which opens the file _either_ for reading (returning a `jsonlines.Reader`) _or_ for writing (returning a `jsonlines.Writer`)

**Comment by wbolster** [comment] 2023-09-13 13:45
actually, this is a duplicate of #72 and #79, and does not contain new information or insights. closing as dup.

**Closed by wbolster** 2023-09-13 13:45 UTC
Labels: duplicate, needs-info

**Comment by marcstreeter** [comment] 2023-09-14 02:17
Dude you're awesome, you responded much faster than I expected. And you're right, I was wrong with this request. I had it in my head that the `+` would create the file if not existing, but that has nothing to do with it. I have no use case for the `+`.  Thank you for closing before I could even respond 👋

**Comment by wbolster** [comment] 2023-09-14 06:06
heh you're welcome. issues that actually aren't issues are my favourite 😃
